# Settings for the app
app:
  # HTML Title
  title: Tektonomastics
  # Header name
  name: Tektonomastics, the building names project
  # Meta description that will show up in Google search results
  meta_description: _(Tektonomatics is mapping the named buildings of NYC and beyond. To qualify for inclusion on the map, buildings must be residential, and visibly named, ideally with the name carved into the frieze on the entablature above the doorway.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.66803632965453
      lng: -73.9534447202459
    zoom: 16
    minZoom: 10
    maxZoom: 19
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  building:
    label: _(Named building)
    rules:
      - condition: '"{{location_type}}" === "building"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]



activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a building)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Inventory)
  show_map_button_label: _(Map)
  action_text: _(added)
  title: _(Add building details)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Add to map)
  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-email
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
        - key: required
    - prompt: _(Building name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Building Name)
        - key: size
          value: 30
        - key: required
    - prompt: _(Street address)
      type: text
      name: address
      attrs:
        - key: placeholder
          value: _(123 Something Street)
        - key: size
          value: 30
        - key: required
    - prompt: _(Town and state)
      type: text
      name: address
      attrs:
        - key: placeholder
          value: _(Brooklyn, NY)
        - key: size
          value: 30
    - type: hidden
      name: location_type
      attrs:
        - key: value
          value: building
    - prompt: _(Optional description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email